const { EmbedBuilder } = require("discord.js");

function createMessage(description, title) {
  return new EmbedBuilder()
    .setDescription(description)
    .setColor("Blue")
    .setTimestamp()
    .setTitle(title);
}

function createMessageImage(title, image) {
  return new EmbedBuilder()
    .setImage(image)
    .setColor("Blue")
    .setTimestamp()
    .setTitle(title);
}

module.exports = {
  embed1_instrucciones: () => createMessageImage("Instrucciones para Calcular Redes - Paso 1", "https://cdn.discordapp.com/attachments/1024063822127968369/1177569090920005702/Paso1.png"),
  embed2_instrucciones: () => createMessageImage("Instrucciones para Calcular Redes - Paso 2", "https://cdn.discordapp.com/attachments/1024063822127968369/1177569110217994291/Paso2.png"),
  embed3_instrucciones: () => createMessageImage("Instrucciones para Calcular Redes - Paso 3", "https://cdn.discordapp.com/attachments/1024063822127968369/1177569135484489838/Paso3.png"),
  embed4_instrucciones: () => createMessageImage("Instrucciones para Calcular Redes - Paso 4", "https://cdn.discordapp.com/attachments/1024063822127968369/1177569152483999764/Paso4.png"),
  embed5_instrucciones: () => createMessageImage("Instrucciones para Calcular Redes - Paso 5", "https://cdn.discordapp.com/attachments/1024063822127968369/1177569167600255107/Captura_de_pantalla_2023-11-14_193447.png"),
  embed1: () => createMessage("**Router:** Conecta y dirige el tráfico entre redes; gestiona direcciones IP y brinda funciones de seguridad.\n\n**Switch:** En la capa de enlace, conecta dispositivos en una LAN, facilita la comunicación selectiva y eficiente.\n\n**Hub:** En la capa física, amplifica señales y envía datos a todos los dispositivos conectados en una red local.\n\n**Patch Panel:** Organiza conexiones de cables en redes, proporcionando un punto centralizado para gestionar y cambiar conexiones.\n\n**Red Ethernet:** Estándar de red LAN que utiliza cables de cobre para transmitir datos a altas velocidades, comúnmente empleado en la conexión de dispositivos locales.", "Definiciones Elementos de un rack"),
  embed2: () => createMessage("**STP (Shielded Twisted Pair):** Cableado Ethernet con pares trenzados protegidos por una cubierta metálica que reduce la interferencia electromagnética, proporcionando mayor inmunidad a las interferencias.\n\n**UTP (Unshielded Twisted Pair):** Cableado Ethernet con pares trenzados sin blindaje metálico. Aunque es más vulnerable a interferencias, es ampliamente utilizado debido a su costo y flexibilidad.\n\n**FTP (Foiled Twisted Pair):** Cableado Ethernet similar al UTP pero con una lámina de blindaje global que envuelve todos los pares trenzados, ofreciendo una mayor protección contra interferencias electromagnéticas.", "Definiciones Tipos de Cables"),
  embed3: () => createMessage("**Espacio de Planta para Equipos de Comunicaciones (EPC):** **Definición:** Área destinada a albergar equipos de comunicaciones, como servidores, switches y dispositivos de red.\n**Propósito:** Brinda un entorno físico y organizado para la instalación y mantenimiento de equipos de telecomunicaciones.\n\n**Espacio de Planta para Equipos de Usuario (EPU):** **Definición:** Área dedicada a alojar los equipos utilizados por los usuarios finales, como computadoras y dispositivos de trabajo.\n**Propósito:** Diseñado para facilitar el acceso y la conectividad de los usuarios a los sistemas de comunicación y redes.\n\n**WA (Working Area):**\n**Definición:** Espacio de trabajo donde los usuarios finales interactúan con los dispositivos de red.\n**Propósito:** Facilita la conectividad directa de dispositivos de usuario y proporciona flexibilidad en la disposición de equipos.\n\n**CP (Consolidation Point):**\n**Definición:** Punto de consolidación para conectar cables de diferentes áreas en una red de cableado.\n**Propósito:** Simplifica la administración del cableado y permite adaptaciones futuras sin alterar la infraestructura principal.\n\n**TR (Telecommunications Room):**\n**Definición:** Sala que alberga el equipo de conexión central para cables de telecomunicaciones.\n**Propósito:** Sirve como punto central de distribución y conexión para facilitar la gestión del cableado.\n\n**ER (Equipment Room):**\n**Definición:** Espacio designado para albergar equipos de telecomunicaciones y servidores.\n**Propósito:** Proporciona un entorno controlado para dispositivos críticos de red y sistemas de almacenamiento.\n\n**EF (Building Entrance Facility):**\n**Definición:** Punto de entrada del cableado de telecomunicaciones en un edificio.\n**Propósito:** Facilita la conexión de la red externa con la infraestructura interna, asegurando un ingreso ordenado y controlado del cableado.", "Definiciones Espacios dentro del SCE"),
  embed4: () => createMessage("**EIA-TIA-568B**\nEIA/TIA-568B es un estándar de cableado estructurado utilizado para el diseño y la implementación de sistemas de cableado en redes de telecomunicaciones, especialmente en entornos de redes Ethernet.\n**Cable Ethernet:** Mantener al menos 15 cm de separación.\n**Cable Eléctrico:** Mantener al menos 30 cm de separación.\n**TIA/606-A:** Definición: La norma TIA/606-A es un estándar de la Industria de Telecomunicaciones de América (TIA) que establece pautas para la administración de infraestructuras de cableado y equipamiento.", "Definiciones sin categoría"),
  embed5: () => createMessage("**100BaseT (Fast Ethernet):** Definición: Estándar de red Ethernet que permite velocidades de 100 Mbps utilizando cables de par trenzado.\n\n**100BaseTX:**\n**Definición:** Variante de Fast Ethernet que utiliza cables de par trenzado para transmisión de datos a 100 Mbps.\n**Características:** Conectividad a través de cable UTP, adecuado para entornos de red de corta distancia.\n\n**100BaseFX Half Duplex:**\n**Definición:** Estándar Fast Ethernet utilizando fibra óptica para transmisión a 100 Mbps en modo semi-dúplex.\n**Características:** La comunicación es bidireccional, pero no simultánea, en una sola fibra.\n\n**100BaseFX Full Duplex:**\n**Definición:** Variante de 100BaseFX que permite la transmisión simultánea en ambos sentidos a 100 Mbps.\n**Características:** Utiliza fibra óptica, permitiendo un flujo continuo de datos en ambas direcciones.", "Definiciones Tipos de redes Ethernet"),
  embed6: () => createMessage("**CAT5:**\n**Definición:** Categoría de cableado que admite velocidades de hasta 1000 Mbps (1 Gbps) a frecuencias de hasta 100 MHz.\n**Uso Actual:** Aunque sigue siendo utilizado, ha sido en gran medida reemplazado por estándares más nuevos.\n\n**CAT5e:**\n**Definición:** Mejora del CAT5, diseñado para reducir interferencias y soportar velocidades de hasta 1000 Mbps a frecuencias de hasta 100 MHz.\n**Uso Actual:** Ampliamente adoptado para redes Gigabit Ethernet.\n\n**CAT6:**\n**Definición:** Categoría de cable con mayor capacidad de transmisión, admite velocidades de hasta 10 Gbps a frecuencias de hasta 250 MHz.\n**Uso Actual:** Común en redes que requieren altas tasas de transferencia, como 10 Gigabit Ethernet.\n\n**CAT6A:**\n**Definición:** Mejora del CAT6, diseñado para admitir velocidades de hasta 10 Gbps a frecuencias de hasta 500 MHz.\n**Uso Actual:** Ideal para aplicaciones que requieren un mayor rendimiento, como 10 Gigabit Ethernet sobre distancias más largas.", "Definiciones Tipos de categorias de par trenzado")
};